In [8]:
from google.colab import files
uploaded = files.upload()

Saving train_u6lujuX_CVtuZ9i (1).csv to train_u6lujuX_CVtuZ9i (1) (2).csv


In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report, confusion_matrix
import io
import plotly.express as px
import plotly.graph_objects as go

In [11]:
df = pd.read_csv(io.BytesIO(uploaded['train_u6lujuX_CVtuZ9i (1) (2).csv']))

df.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [12]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [14]:
#mediana (float)
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].median())
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median())
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].median())

#moda (categorii)
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])
df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mode()[0])
df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])

In [15]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [16]:
for column in ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status']:
    df[column] = LabelEncoder().fit_transform(df[column])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             614 non-null    int64  
 2   Married            614 non-null    int64  
 3   Dependents         614 non-null    object 
 4   Education          614 non-null    int64  
 5   Self_Employed      614 non-null    int64  
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    int64  
 12  Loan_Status        614 non-null    int64  
dtypes: float64(4), int64(7), object(2)
memory usage: 62.5+ KB


In [18]:
# 3+ -> 3
df['Dependents'] = df['Dependents'].replace('3+', 3).astype(int)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             614 non-null    int64  
 2   Married            614 non-null    int64  
 3   Dependents         614 non-null    int64  
 4   Education          614 non-null    int64  
 5   Self_Employed      614 non-null    int64  
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    int64  
 12  Loan_Status        614 non-null    int64  
dtypes: float64(4), int64(8), object(1)
memory usage: 62.5+ KB


In [20]:
df.head(5)

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001002       1        0           0          0              0   
1  LP001003       1        1           1          0              0   
2  LP001005       1        1           0          0              1   
3  LP001006       1        1           0          1              0   
4  LP001008       1        0           0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0       128.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              0            0  
2             1.0              2            1  
3             1.0              2            1  
4             1.0              2            1

In [21]:
fig1 = px.histogram(df, x='ApplicantIncome', nbins=30, marginal='rug', title='Распределение доходов заявителей',
                    color_discrete_sequence=['skyblue'])
fig1.show()

In [22]:
fig2 = px.histogram(df, x='Credit_History', color='Loan_Status', barmode='group',
                    title='Одобрение кредита в зависимости от кредитной истории',
                    color_discrete_sequence=['#FF9999', '#66B2FF'])
fig2.show()

In [23]:
numeric_df = df.select_dtypes(include=[np.number])
corr_matrix = numeric_df.corr()
fig3 = go.Figure(data=go.Heatmap(z=corr_matrix.values, x=corr_matrix.columns, y=corr_matrix.columns,
                                 colorscale='RdBu', text=corr_matrix.round(2).values, texttemplate="%{text}"))
fig3.update_layout(title='Корреляционная матрица', width=600, height=600)
fig3.show()

In [24]:
fig4 = px.scatter(df, x='ApplicantIncome', y='LoanAmount', color='Loan_Status',
                  title='Сумма кредита vs Доход', color_discrete_sequence=['#FF9999', '#66B2FF'])
fig4.show()

In [25]:
X = df.drop(['Loan_ID', 'Loan_Status'], axis=1)
# Tzelevaya
y = df['Loan_Status']

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
def results(model, X_train, X_test, y_train, y_test, model_name):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]

    print(f"\n{model_name} Оценка:")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.3f}")
    print(f"Precision: {precision_score(y_test, y_pred):.3f}")
    print(f"Recall: {recall_score(y_test, y_pred):.3f}")
    print(f"F1-Score: {f1_score(y_test, y_pred):.3f}")
    print(f"ROC-AUC: {roc_auc_score(y_test, y_pred_proba):.3f}")
    print("\nКлассификация:")
    print(classification_report(y_test, y_pred))
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    cv_roc = cross_val_score(model, X, y, cv=5, scoring='roc_auc').mean()
    print(f"{model_name} CV ROC-AUC: {cv_roc:.3f}")
    return cv_roc

In [28]:
from catboost import CatBoostClassifier
from sklearn.model_selection import cross_val_score

catboost_model = CatBoostClassifier(iterations=100, depth=6, learning_rate=0.1, verbose=0, random_state=42)
catboost_cv_roc = results(catboost_model, X_train, X_test, y_train, y_test, "CatBoost")


CatBoost Оценка:
Accuracy: 0.789
Precision: 0.760
Recall: 0.988
F1-Score: 0.859
ROC-AUC: 0.736

Классификация:
              precision    recall  f1-score   support

           0       0.95      0.42      0.58        43
           1       0.76      0.99      0.86        80

    accuracy                           0.79       123
   macro avg       0.85      0.70      0.72       123
weighted avg       0.83      0.79      0.76       123


Confusion Matrix:
[[18 25]
 [ 1 79]]
CatBoost CV ROC-AUC: 0.755


In [29]:
#       Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_cv_roc = results(rf_model, X_train, X_test, y_train, y_test, "Random Forest")


Random Forest Оценка:
Accuracy: 0.756
Precision: 0.750
Recall: 0.938
F1-Score: 0.833
ROC-AUC: 0.755

Классификация:
              precision    recall  f1-score   support

           0       0.78      0.42      0.55        43
           1       0.75      0.94      0.83        80

    accuracy                           0.76       123
   macro avg       0.77      0.68      0.69       123
weighted avg       0.76      0.76      0.73       123


Confusion Matrix:
[[18 25]
 [ 5 75]]
Random Forest CV ROC-AUC: 0.766


In [30]:
from sklearn.linear_model import LogisticRegression
#         Logistic Regression
lr_model = LogisticRegression(max_iter=10000, random_state=42)
lr_cv_roc = results(lr_model, X_train, X_test, y_train, y_test, "Logistic Regression")


Logistic Regression Оценка:
Accuracy: 0.789
Precision: 0.760
Recall: 0.988
F1-Score: 0.859
ROC-AUC: 0.739

Классификация:
              precision    recall  f1-score   support

           0       0.95      0.42      0.58        43
           1       0.76      0.99      0.86        80

    accuracy                           0.79       123
   macro avg       0.85      0.70      0.72       123
weighted avg       0.83      0.79      0.76       123


Confusion Matrix:
[[18 25]
 [ 1 79]]
Logistic Regression CV ROC-AUC: 0.726


In [36]:
comparison_models = pd.DataFrame({
    'Model': ['CatBoost', 'Random Forest', 'Logistic Regression'],
    'CV ROC-AUC': [catboost_cv_roc, rf_cv_roc, lr_cv_roc]
})
comparison_models

Model  CV ROC-AUC
0             CatBoost    0.754640
1        Random Forest    0.766117
2  Logistic Regression    0.725592

In [37]:
fig5 = px.bar(comparison_models, x='Model', y='CV ROC-AUC', title='Сравнение моделей по CV ROC-AUC',text=comparison_models['CV ROC-AUC'].round(3))
fig5.show()

In [38]:
vazhnost = pd.DataFrame({'Feature': X.columns, 'Importance': rf_model.feature_importances_})
vazhnost = vazhnost.sort_values('Importance', ascending=False)
fig6 = px.bar(vazhnost, x='Feature', y='Importance', title='Важность признаков (Random Forest)')
fig6.show()